#!/usr/bin/env bash

FILE=""
LOCALITY=""

function locality() {
  parse_args "$@"

  modify_file_name "${FILE}" "${LOCALITY}"
}

# Parse arguments of command
#
# Arguments:
# 
#   $1 - The file path. If not set the current file path will be used
#   $2 - The locality. If not set the locality from the configuration file is used
# 
function parse_args() {
  if [[ -z "$1" ]]; then 
    FILE=$(get_calling_file "$@")
  else 
    FILE="$1";
  fi

  if [[ -z "$2" ]]; then 
    LOCALITY=$(read_locality_config) || { echo "Failed to read locality configuration. Make sure that '~/.config/.locality' exists and contains 'LOCALITY=<your-locality>'"; exit 1; }
  else 
    LOCALITY="$2";
  fi
}

# Get the name of the calling script 
#
# See here: https://www.experts-exchange.com/questions/25025178/Determine-the-name-of-a-calling-Bash-script.html
function get_calling_file() {
  realpath "$(ps -f -p $PPID | tail -1 | awk '{print $NF}')"
}

# Read locality variable by sourcing configuration file '~/.config/.locality'
function read_locality_config() {
  locality_config="${HOME}/.config/.locality"
  
  if [[ ! -f ${locality_config} ]]; then exit 1; fi

  source "$locality_config"

  if [[ -z $LOCALITY ]]; then exit 1; fi
  echo "${LOCALITY}"
}

function usage() {
  echo "usage"
}


# Prepends a string to the file name in the given path
#
# Arguments:
# 
#   $1 - The file path
#   $2 - The string to prepend
# 
# Examples: 
#  
#  modify_file_name ~/test/.zshrc loc1 -> ~/test/loc1.zshrc
#
function modify_file_name() {
  local filePath=$1
  local locality=$2
  local regex="^(.+/)(\.)?([^/]+)$"
  sed -E 's|'"${regex}"'|\1\2'"${locality}"'.\3|' <<< "${filePath}"
}

# Check if program is executed directly from the command line or sourced
# 
# See https://stackoverflow.com/a/23009039/2553104
function sourced() {
  [ "${0}" != "${BASH_SOURCE[0]}" ]  
}

function handle_error() {
  echo "An error occured, exit code $?"
}

trap 'handle_error $?' ERR

if ! sourced; then locality "$@"; fi
